#ifndef VLCMEDIAPLAYER_GLOBAL_H
#define VLCMEDIAPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VLCMEDIAPLAYER_LIBRARY)
#  define VLCMEDIAPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VLCMEDIAPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VLCMEDIAPLAYER_GLOBAL_H
